apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f0mrfdmrh-nodejs 
  janus-idp.io/tekton: f0mrfdmrh-nodejs
  backstage.io/kubernetes-id: f0mrfdmrh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f0mrfdmrh-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml